# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProductsCleanMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductsCleanMVVM

  target 'ProductsCleanMVVMSanpshotTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'iOSSnapshotTestCase'
  end

  target 'ProductsCleanMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProductsCleanMVVMUITests' do
    # Pods for testing
  end

end
